### ISSUE TITLE
error: macro "RETURN_STRINGL" passed 3 arguments, but takes just 2 

### ISSUE THREAD

**Issue by lostmilky** [timtoday/snowflake-php#1]
Build with PHP7.2
snowflake.c:67:29: error: macro "RETURN_STRINGL" passed 3 arguments, but takes just 2
  RETURN_STRINGL(strg, len, 0);

modify line 67         
RETURN_STRINGL(strg, len);
then:
make && make install
success
